//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita_medicas
    {
        public int id { get; set; }
        public int id_medico { get; set; }
        public string nombre_medico { get; set; }
        public string apellido_medico { get; set; }
        public string especialidad { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public System.DateTime hora_fin { get; set; }
        public int id_paciente { get; set; }
        public string nombre_paciente { get; set; }
        public int estado_cita { get; set; }
        public int documento { get; set; }
        public string apellido_paciente { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    }
}
