//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados_medicos
    {
        public int id { get; set; }
        public int id_medico { get; set; }
        public long ident_medico { get; set; }
        public string nombre_medico { get; set; }
        public string apellido_medico { get; set; }
        public int estado_agenda { get; set; }
        public int estado_horario { get; set; }
        public string especialidad { get; set; }
        public Nullable<int> horas_semana { get; set; }
    }
}
