//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historia_clinica
    {
        public long id { get; set; }
        public string nombre_paciente { get; set; }
        public int documento_paciente { get; set; }
        public string motivo_consulta { get; set; }
        public string alergias { get; set; }
        public string cirugias { get; set; }
        public int altura { get; set; }
        public int peso { get; set; }
        public string observacion_piel { get; set; }
        public string observacion_respiracion { get; set; }
        public string observacion_boca { get; set; }
        public string diagnostico { get; set; }
        public string apellido_paciente { get; set; }
        public string nombre_medico { get; set; }
        public string especialidad { get; set; }
        public string apellido_medico { get; set; }
        public int id_medico { get; set; }
        public int id_paciente { get; set; }
        public System.DateTime fecha_atencion { get; set; }
        public string asignar_especialista { get; set; }
        public Nullable<int> estado { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    }
}
