//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqrs
    {
        public long id { get; set; }
        public string tipo_mensaje { get; set; }
        public string mensaje { get; set; }
        public string responder_mensaje { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public string session { get; set; }
        public int id_usuario { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    }
}
