//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios_seguridad
    {
        public int id_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string clave_cliente { get; set; }
        public string token_generado { get; set; }
        public Nullable<System.DateTime> fecha_vigencia { get; set; }
        public string token_seguridad { get; set; }
    }
}
