//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.token_repureacion_usuario = new HashSet<token_repureacion_usuario>();
        }
    
        public long id { get; set; }
        public string apellidos { get; set; }
        public string nombres { get; set; }
        public Nullable<long> identificacion { get; set; }
        public string email { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_rol { get; set; }
        public string session { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string especialidad { get; set; }
        public string foto { get; set; }
        public string url { get; set; }
    
        public virtual roles roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<token_repureacion_usuario> token_repureacion_usuario { get; set; }
    }
}
